# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "codenames-api"
main = "src/index.ts"
compatibility_date = "2024-11-18"

send_metrics = false

[durable_objects]
bindings = [
  { name = "CODENAMES", class_name = "CodenamesGame" }
]

routes = [
  { pattern = "api.codenam.es", custom_domain = true }
]

[env.local]
vars = { WORKER_ENV = "local" }
[env.local.durable_objects]
  bindings = [
    { name = "CODENAMES", class_name = "CodenamesGame" }
  ]

[[migrations]]
tag = "v1" # Should be unique for each new migration
new_classes = ["CodenamesGame"]

[limits]
cpu_ms = 100

[observability]
enabled = true